# Generated by Django 4.2.5 on 2023-09-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='State',
        ),
    ]
