# Generated by Django 4.2.5 on 2023-09-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_rename_place_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='Place',
        ),
    ]
