# Generated by Django 4.2.5 on 2023-09-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_teams'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='about',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='members',
            new_name='name',
        ),
    ]
