# Generated by Django 4.2.5 on 2023-09-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_delete_place_rename_about_teams_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pics')),
                ('about', models.TextField()),
            ],
        ),
    ]
